Repository Saerom-teo/server, pull requests merged in 2024-07, with the labels that each got.

#149 🌟(#96) 관리자 페이지, 유저페이지
  src/main/java/com/saeromteo/app/controller/notice/NoticeController.java
  src/main/java/com/saeromteo/app/controller/question/QuestionController.java
  src/main/java/com/saeromteo/app/dao/question/QuestionDAO.java
  src/main/resources/mybatis/mappers/questionMapper.xml
  src/main/resources/static/css/faq.css
  src/main/resources/static/css/notice.css
  src/main/resources/static/css/question.css
  src/main/resources/static/js/faq.js
  src/main/resources/static/js/question.js
  src/main/webapp/WEB-INF/views/admin/notice-manager.jsp
  src/main/webapp/WEB-INF/views/admin/question-manager.jsp
  src/main/webapp/WEB-INF/views/editor/editor-question-form.jsp
  src/main/webapp/WEB-INF/views/notice/notice.jsp
  src/main/webapp/WEB-INF/views/question/question-write.jsp
  src/main/webapp/WEB-INF/views/question/question.jsp
Labels: 🎨design, 🌟feature

#150 🌟(#115) 주문 내역 상세 조회
  src/main/java/com/saeromteo/app/controller/orderInquiry/OrderInquiryController.java
  src/main/java/com/saeromteo/app/dao/orderInquiry/OrderInquiryDao.java
  src/main/resources/mybatis/mappers/orderInquiryMapper.xml
  src/main/resources/static/css/afterSales.css
  src/main/resources/static/css/orderDetailnquriy.css
  src/main/webapp/WEB-INF/views/afterSales/afterSales.jsp
  src/main/webapp/WEB-INF/views/orderInquiry/orderDetailnquriy.html
  src/main/webapp/WEB-INF/views/orderInquiry/orderDetailnquriy.jsp
  src/main/webapp/WEB-INF/views/orderInquiry/orderInquiry.jsp
Labels: 🎨design, 🌟feature

#151 🌟(#145) 상품 후기 기능
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/java/com/saeromteo/app/controller/review/ReviewController.java
  src/main/java/com/saeromteo/app/controller/review/ReviewFrontController.java
  src/main/java/com/saeromteo/app/dao/review/ReviewDao.java
  src/main/java/com/saeromteo/app/dao/review/ReviewInterface.java
  src/main/java/com/saeromteo/app/dao/review/ReviewSearchDto.java
  src/main/java/com/saeromteo/app/service/review/ReviewService.java
  src/main/resources/mybatis/mappers/reviewMapper.xml
  src/main/resources/static/css/product-detail-review.css
  src/main/resources/static/css/review.css
  src/main/webapp/WEB-INF/views/product/product-detail-review.jsp
  src/main/webapp/WEB-INF/views/product/product-detail.jsp
  src/main/webapp/WEB-INF/views/review/review.jsp
Labels: 🌟feature

#152 🌟(#147) 위시리스트, 상품 카테고리 구현/ 관리자 페이지
  src/main/java/com/saeromteo/app/controller/admin/AdminController.java
  src/main/java/com/saeromteo/app/controller/product/DiscountController.java
  src/main/java/com/saeromteo/app/controller/product/ProductCategoryController.java
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/resources/mybatis/mappers/discountMapper.xml
  src/main/resources/mybatis/mappers/productCategoryMapper.xml
  src/main/resources/mybatis/mappers/productMapper.xml
  src/main/resources/static/css/product.css
  src/main/resources/static/css/shopnav.css
  src/main/webapp/WEB-INF/views/admin/product-category-manager.jsp
  src/main/webapp/WEB-INF/views/admin/product-discount-manager.jsp
  src/main/webapp/WEB-INF/views/admin/product-manager.jsp
  src/main/webapp/WEB-INF/views/admin/side-nav.jsp
  src/main/webapp/WEB-INF/views/common/shopnav.jsp
  src/main/webapp/WEB-INF/views/product/product-detail.jsp
  src/main/webapp/WEB-INF/views/product/product.jsp
Labels: 🌟feature

#157 🌟(#138 ) 위시리스트 페이징 및 디자인 수정
  .factorypath
  src/main/java/com/saeromteo/app/controller/admin/AdminApiController.java
  src/main/java/com/saeromteo/app/controller/admin/AdminController.java
  src/main/java/com/saeromteo/app/controller/notice/NoticeController.java
  src/main/java/com/saeromteo/app/controller/question/QuestionController.java
  src/main/java/com/saeromteo/app/controller/wishlist/WishlistController.java
  src/main/java/com/saeromteo/app/dao/notice/NoticeDAO.java
  src/main/java/com/saeromteo/app/dao/notice/NoticeDAOInterface.java
  src/main/java/com/saeromteo/app/dao/question/QuestionDAO.java
  src/main/java/com/saeromteo/app/dao/question/QuestionDAOInterface.java
  src/main/java/com/saeromteo/app/dao/wishlist/WishlistDAO.java
  src/main/java/com/saeromteo/app/dto/notice/NoticeEntity.java
  src/main/java/com/saeromteo/app/model/notice/NoticeDTO.java
  src/main/java/com/saeromteo/app/model/question/QuestionDTO.java
  src/main/java/com/saeromteo/app/service/notice/NoticeService.java
  src/main/java/com/saeromteo/app/service/question/QuestionService.java
  src/main/java/com/saeromteo/app/service/wishlist/WishlistService.java
  src/main/resources/mybatis/NoticeSqlMapConfig.xml
  src/main/resources/mybatis/QuestionSqlMapConfig.xml
  src/main/resources/mybatis/mappers/wishlistMapper.xml
  src/main/resources/static/css/mypage-nav.css
  src/main/resources/static/css/question.css
  src/main/resources/static/css/style.css
  src/main/resources/static/css/wishlist.css
  src/main/resources/static/icon/111.png
  src/main/resources/static/icon/mypage-profile.svg
  src/main/resources/static/js/style.js
  src/main/webapp/WEB-INF/views/collection/footer.jsp
  src/main/webapp/WEB-INF/views/collection/header.jsp
  src/main/webapp/WEB-INF/views/common/mypage-nav.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-wishlist.jsp
  src/main/webapp/WEB-INF/views/notice/notice.jsp
  src/main/webapp/WEB-INF/views/question/question-write.jsp
  src/main/webapp/WEB-INF/views/question/question.jsp
Labels: 🎨design, 🌟feature

#156 🌟(#146) 포인트 조회 페이지 제작
  src/main/java/com/saeromteo/app/controller/MainController.java
  src/main/java/com/saeromteo/app/controller/admin/AdminController.java
  src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java
  src/main/java/com/saeromteo/app/controller/mypage/MyPageController.java
  src/main/java/com/saeromteo/app/controller/point/PointController.java
  src/main/java/com/saeromteo/app/dao/point/PointDao.java
  src/main/java/com/saeromteo/app/model/point/PointDto.java
  src/main/java/com/saeromteo/app/model/point/PointEntity.java
  src/main/java/com/saeromteo/app/service/collection/CollectionService.java
  src/main/java/com/saeromteo/app/service/point/PointService.java
  src/main/resources/mybatis/mappers/collectionMapper.xml
  src/main/resources/mybatis/mappers/pointMapper.xml
  src/main/resources/static/css/main.css
  src/main/resources/static/css/mypage-collection.css
  src/main/resources/static/js/admin/collection-manager.js
  src/main/webapp/WEB-INF/views/admin/collection-manager.jsp
  src/main/webapp/WEB-INF/views/admin/collection-manager2.jsp
  src/main/webapp/WEB-INF/views/common/mypage-nav.jsp
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/main2.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-collection.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-point.jsp
Labels: 🎨design, 🌟feature

#159 🌟(#138) 상품,상품 상세 페이지 수정
  src/main/java/com/saeromteo/app/controller/product/ProductCategoryController.java
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/java/com/saeromteo/app/controller/wishlist/WishlistController.java
  src/main/java/com/saeromteo/app/dao/product/ProductCategoryDAO.java
  src/main/java/com/saeromteo/app/model/product/ProductEntity.java
  src/main/java/com/saeromteo/app/service/product/ProductCategoryService.java
  src/main/resources/mybatis/mappers/productCategoryMapper.xml
  src/main/resources/static/css/product-detail-review.css
  src/main/resources/static/css/product.css
  src/main/webapp/WEB-INF/views/admin/side-nav.jsp
  src/main/webapp/WEB-INF/views/product/product-detail.jsp
  src/main/webapp/WEB-INF/views/product/product.jsp
Labels: 🔄️refactoring

#160 🌟(#115) 주문 상세 조회
  src/main/java/com/saeromteo/app/controller/afterSales/AfterSalesController.java
  src/main/java/com/saeromteo/app/controller/orderInquiry/OrderInquiryController.java
  src/main/resources/static/css/orderDetailnquriy.css
  src/main/resources/static/css/orderInquiry.css
  src/main/webapp/WEB-INF/views/orderInquiry/orderDetailnquriy.jsp
  src/main/webapp/WEB-INF/views/orderInquiry/orderInquiry.jsp
Labels: 🎨design

#161 🌟(#145 ) 상품 후기 기능
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/java/com/saeromteo/app/controller/review/ReviewController.java
  src/main/java/com/saeromteo/app/controller/review/ReviewFrontController.java
  src/main/java/com/saeromteo/app/dao/product/ProductDAO.java
  src/main/java/com/saeromteo/app/dao/review/ReviewDao.java
  src/main/java/com/saeromteo/app/dto/review/ReviewDateDto.java
  src/main/java/com/saeromteo/app/dto/review/ReviewDetailDto.java
  src/main/java/com/saeromteo/app/service/product/ProductService.java
  src/main/java/com/saeromteo/app/service/review/ReviewService.java
  src/main/resources/mybatis/ReviewSqlMapConfig.xml
  src/main/resources/mybatis/mappers/productMapper.xml
  src/main/resources/mybatis/mappers/reviewMapper.xml
  src/main/resources/static/css/product-detail-review.css
  src/main/resources/static/css/review.css
  src/main/webapp/WEB-INF/views/product/product-detail-review.jsp
  src/main/webapp/WEB-INF/views/review/review.jsp
Labels: 🌟feature

#164 🌟(#146) 수거, 포인트에서 유저와 연결
  src/main/java/com/saeromteo/app/config/SecurityConfig.java
  src/main/java/com/saeromteo/app/controller/admin/AdminController.java
  src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java
  src/main/java/com/saeromteo/app/controller/collection/CollectionController.java
  src/main/java/com/saeromteo/app/controller/mypage/MyPageController.java
  src/main/java/com/saeromteo/app/controller/point/PointController.java
  src/main/java/com/saeromteo/app/dao/user/UserDAO.java
  src/main/java/com/saeromteo/app/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/saeromteo/app/model/point/PointEntity.java
  src/main/java/com/saeromteo/app/service/user/UserService.java
  src/main/java/com/saeromteo/app/util/RankUtil.java
  src/main/resources/mybatis/mappers/pointMapper.xml
  src/main/resources/mybatis/mappers/userMapper.xml
  src/main/resources/static/css/mypage-nav.css
  src/main/resources/static/icon/mypage-profile.svg
  src/main/resources/static/js/collection/service.js
  src/main/resources/static/js/mypage/mypage-collection.js
  src/main/webapp/WEB-INF/views/admin/point-manager.jsp
  src/main/webapp/WEB-INF/views/collection/header.jsp
  src/main/webapp/WEB-INF/views/common/mypage-nav.jsp
Labels: 🎨design, 🌟feature

#166 🌟(#138) 상품 카테고리 수정
  src/main/java/com/saeromteo/app/controller/admin/AdminController.java
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/java/com/saeromteo/app/controller/review/ReviewController.java
  src/main/java/com/saeromteo/app/dao/product/ProductCategoryDAO.java
  src/main/java/com/saeromteo/app/model/product/ProductEntity.java
  src/main/java/com/saeromteo/app/service/product/ProductCategoryService.java
  src/main/resources/mybatis/mappers/productMapper.xml
  src/main/resources/static/css/product-detail-review.css
  src/main/resources/static/css/product.css
  src/main/resources/static/css/wishlist.css
  src/main/webapp/WEB-INF/views/admin/product-discount-manager.jsp
  src/main/webapp/WEB-INF/views/admin/product-manager.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-basket.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-wishlist.jsp
  src/main/webapp/WEB-INF/views/product/product-detail.jsp
  src/main/webapp/WEB-INF/views/product/product.jsp
Labels: 🐞bugfix, 🔄️refactoring

#167 🌟(#115) 주문 내역 상세 조회 및 환불 페이지
  src/main/java/com/saeromteo/app/controller/afterSales/AfterSalesController.java
  src/main/java/com/saeromteo/app/controller/orderInquiry/OrderInquiryController.java
  src/main/java/com/saeromteo/app/service/orderInquiry/OrderInquiryService.java
  src/main/resources/mybatis/mappers/orderInquiryMapper.xml
  src/main/resources/static/css/basket.css
  src/main/resources/static/css/orderInquiry.css
  src/main/resources/static/css/refund.css
  src/main/webapp/WEB-INF/views/afterSales/afterSales.jsp
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/orderInquiry/orderDetailnquriy.jsp
  src/main/webapp/WEB-INF/views/orderInquiry/orderInquiry.jsp
  src/main/webapp/WEB-INF/views/refund/refund.jsp
Labels: 🎨design, 🌟feature

#168 🌟(#126 ) 헤더 토글작업
  src/main/resources/static/css/style.css
  src/main/resources/static/icon/mypage-toggle/bag-frame.svg
  src/main/resources/static/icon/mypage-toggle/chevron-left.svg
  src/main/resources/static/icon/mypage-toggle/chevron-right.svg
  src/main/resources/static/icon/mypage-toggle/credit-card.svg
  src/main/resources/static/icon/mypage-toggle/gear.svg
  src/main/resources/static/icon/mypage-toggle/heart.svg
  src/main/resources/static/icon/mypage-toggle/mypage-order.png
  src/main/resources/static/icon/mypage-toggle/point.svg
  src/main/resources/static/icon/mypage-toggle/receipt.svg
  src/main/resources/static/icon/mypage-toggle/right.svg
  src/main/resources/static/icon/mypage-toggle/truck.svg
  src/main/resources/static/js/style.js
  src/main/webapp/WEB-INF/views/collection/header.jsp
Labels: 🎨design

#169 🌟(#163 #161 ) 상품 후기, 대시보드 css, 헤더 검색 기능
  Dockerfile
  pom.xml
  src/main/java/com/saeromteo/app/controller/admin/AdminController.java
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/java/com/saeromteo/app/controller/review/ReviewController.java
  src/main/java/com/saeromteo/app/dao/product/ProductDAO.java
  src/main/java/com/saeromteo/app/dao/review/ReviewDao.java
  src/main/java/com/saeromteo/app/dto/review/ReviewDetailDto.java
  src/main/java/com/saeromteo/app/service/product/ProductService.java
  src/main/java/com/saeromteo/app/service/quiz/QuizHistoryService.java
  src/main/java/com/saeromteo/app/service/review/ReviewService.java
  src/main/resources/mybatis/mappers/productMapper.xml
  src/main/resources/mybatis/mappers/reviewMapper.xml
  src/main/resources/static/css/dashboard.css
  src/main/resources/static/css/envdata.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/news.css
  src/main/resources/static/css/product.css
  src/main/resources/static/css/quiz.css
  src/main/resources/static/css/style.css
  src/main/resources/static/img/banner1.png
  src/main/resources/static/img/banner2.png
  src/main/resources/static/img/banner3.png
  src/main/webapp/WEB-INF/views/admin/review-manager.jsp
  src/main/webapp/WEB-INF/views/admin/side-nav.jsp
  src/main/webapp/WEB-INF/views/collection/header.jsp
  src/main/webapp/WEB-INF/views/common/dashboard-nav.jsp
  src/main/webapp/WEB-INF/views/dashboard/dashboard.jsp
  src/main/webapp/WEB-INF/views/dashboard/envdata.jsp
  src/main/webapp/WEB-INF/views/dashboard/envdetail.jsp
  src/main/webapp/WEB-INF/views/dashboard/news.jsp
  src/main/webapp/WEB-INF/views/dashboard/quiz.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/product/product-detail-review.jsp
  src/main/webapp/WEB-INF/views/product/product-search.jsp
  src/main/webapp/WEB-INF/views/review/review.jsp
Labels: 🎨design, 🌟feature

#172 🌟(#146) header 충돌 복구
  src/main/webapp/WEB-INF/views/collection/header.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-collection.jsp
Labels: 🐞bugfix

#173 🌟(#146) 포인트 관리자 페이지 제작
  src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java
  src/main/java/com/saeromteo/app/controller/mypage/MyPageController.java
  src/main/java/com/saeromteo/app/controller/point/PointController.java
  src/main/java/com/saeromteo/app/model/point/PointDto.java
  src/main/java/com/saeromteo/app/service/collection/CollectionService.java
  src/main/java/com/saeromteo/app/service/point/PointService.java
  src/main/resources/mybatis/mappers/pointMapper.xml
  src/main/resources/static/js/admin/point-manager.js
  src/main/webapp/WEB-INF/views/admin/point-manager.jsp
  src/main/webapp/WEB-INF/views/collection/regist-complete.jsp
  src/main/webapp/WEB-INF/views/collection/request-complete.jsp
  src/main/webapp/WEB-INF/views/common/mypage-nav.jsp
Labels: 🎨design, 🌟feature

#177 🌟(#163) 에디터 적용 시도 및 경로 설정
  src/main/webapp/WEB-INF/views/admin/envdata-manager.jsp
  src/main/webapp/WEB-INF/views/admin/news-manager.jsp
  src/main/webapp/WEB-INF/views/admin/quiz-manager.jsp
  src/main/webapp/WEB-INF/views/dashboard/dashboard.jsp
  src/main/webapp/WEB-INF/views/dashboard/envdata.jsp
  src/main/webapp/WEB-INF/views/dashboard/envdetail.jsp
  src/main/webapp/WEB-INF/views/dashboard/news.jsp
  src/main/webapp/WEB-INF/views/dashboard/quiz.jsp
  src/main/webapp/WEB-INF/views/editor/editor-envdata-form.jsp
  src/main/webapp/WEB-INF/views/review/review.jsp
Labels: 🌟feature

#179 🌟(#138) 상품 카테고리 정렬
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/java/com/saeromteo/app/dao/product/ProductDAO.java
  src/main/java/com/saeromteo/app/model/product/ProductEntity.java
  src/main/java/com/saeromteo/app/service/product/ProductService.java
  src/main/resources/mybatis/mappers/productMapper.xml
  src/main/webapp/WEB-INF/views/product/product.jsp
Labels: 🌟feature

#182 dockerignore파일 수정
  .dockerignore
  src/main/java/com/saeromteo/app/controller/mypage/MyPageController.java
  src/main/java/com/saeromteo/app/dao/orderInquiry/OrderInquiryDao.java
  src/main/java/com/saeromteo/app/service/orderInquiry/OrderInquiryService.java
  src/main/resources/mybatis/mappers/orderInquiryMapper.xml
  src/main/webapp/WEB-INF/views/common/mypage-nav.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-order-detail.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-order-list.jsp
Labels: 🔄️refactoring

#189 🌟(#180 ) 메인 페이지 수정
  src/main/java/com/saeromteo/app/controller/MainController.java
  src/main/java/com/saeromteo/app/controller/basket/BasketController.java
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/java/com/saeromteo/app/controller/wishlist/WishlistController.java
  src/main/java/com/saeromteo/app/dao/product/ProductDAO.java
  src/main/java/com/saeromteo/app/service/product/ProductService.java
  src/main/resources/mybatis/mappers/basketMapper.xml
  src/main/resources/mybatis/mappers/productMapper.xml
  src/main/resources/mybatis/mappers/wishlistMapper.xml
  src/main/resources/static/css/basket.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/product-detail-review.css
  src/main/resources/static/css/wishlist.css
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-basket.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-wishlist.jsp
  src/main/webapp/WEB-INF/views/product/product-detail.jsp
  src/main/webapp/WEB-INF/views/product/product.jsp
Labels: 🌟feature, 🔄️refactoring

#191 🌟(#163 ) etc
  .Dockerfile.swp
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/resources/static/css/dashboard.css
  src/main/resources/static/css/envdata.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/news.css
  src/main/resources/static/css/product.css
  src/main/resources/static/css/quiz.css
  src/main/resources/static/css/shopnav.css
  src/main/resources/static/css/vars.css
  src/main/resources/static/icon/up.svg
  src/main/resources/static/img/main-img-1.png
  src/main/resources/static/img/main-img-3.png
  src/main/resources/static/img/quiz-back.png
  src/main/webapp/WEB-INF/views/admin/envdata-manager.jsp
  src/main/webapp/WEB-INF/views/collection/header.jsp
  src/main/webapp/WEB-INF/views/common/dashboard-nav.jsp
  src/main/webapp/WEB-INF/views/common/shopnav.jsp
  src/main/webapp/WEB-INF/views/dashboard/dashboard.jsp
  src/main/webapp/WEB-INF/views/dashboard/envdetail.jsp
  src/main/webapp/WEB-INF/views/dashboard/news.jsp
  src/main/webapp/WEB-INF/views/dashboard/quiz.jsp
  src/main/webapp/WEB-INF/views/editor/editor-envdata-form.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/product/product-detail-review.jsp
  src/main/webapp/WEB-INF/views/product/product-detail.jsp
  src/main/webapp/WEB-INF/views/product/product.jsp
Labels: 🎨design, 🌟feature

#198 🌟(#148) 메인페이지 글자 간격 조절
  .factorypath
  exit
  src/main/resources/static/css/main.css
Labels: 🎨design

#201 [Chore] modify image name
  pom.xml
Labels: 🎨design

#213 🌟(#181) 마이페이지 주문 프론트 제작
  src/main/java/com/saeromteo/app/controller/mypage/MyPageController.java
  src/main/resources/static/css/mypage-order.css
  src/main/resources/static/css/mypage-orderlist.css
  src/main/webapp/WEB-INF/views/mypage/mypage-order-detail.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-order-list.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-order-return.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-orderlist.jsp
Labels: 🎨design, 🌟feature

#214 🌟(#148 ) 페이지, 헤더토글 widrh 반응형
  src/main/java/com/saeromteo/app/controller/admin/AdminController.java
  src/main/java/com/saeromteo/app/controller/question/QuestionController.java
  src/main/java/com/saeromteo/app/service/question/FileService.java
  src/main/resources/static/css/faq.css
  src/main/resources/static/css/notice.css
  src/main/resources/static/css/question.css
  src/main/resources/static/css/style.css
  src/main/webapp/WEB-INF/views/admin/notice-manager.jsp
  src/main/webapp/WEB-INF/views/editor/editor-notice-form.jsp
  src/main/webapp/WEB-INF/views/question/question-write.jsp
Labels: 🎨design

#216 🌟(#148) 관리자 페이지 경로 수정
  src/main/webapp/WEB-INF/views/admin/notice-manager.jsp
  src/main/webapp/WEB-INF/views/editor/editor-notice-form.jsp
Labels: 🐞bugfix

#220 🌟(#115) 주문 완료 후 페이지 이동
  src/main/java/com/saeromteo/app/controller/order/OrderController.java
  src/main/resources/static/css/orderAfter.css
  src/main/resources/static/img/tree1.png
  src/main/resources/static/img/tree2.png
  src/main/webapp/WEB-INF/views/order/afterOrder.jsp
  src/main/webapp/WEB-INF/views/order/orderpage.jsp
Labels: 🌟feature

#222 🌟(#163 ) 수정사항
  src/main/java/com/saeromteo/app/config/SecurityConfig.java
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/resources/mybatis/mappers/reviewMapper.xml
  src/main/resources/static/css/dashboard.css
  src/main/resources/static/css/envdetail.css
  src/main/resources/static/css/style.css
  src/main/webapp/WEB-INF/views/dashboard/news.jsp
  src/main/webapp/WEB-INF/views/product/product-detail-review.jsp
Labels: 🌟feature

#225 🌟(#148 ) 헤더토글 경로 추가
  .factorypath
  src/main/webapp/WEB-INF/views/admin/question-manager.jsp
  src/main/webapp/WEB-INF/views/collection/header.jsp
  src/main/webapp/WEB-INF/views/editor/editor-question-form.jsp
  src/main/webapp/WEB-INF/views/question/question-write.jsp
Labels: 🌟feature

#230 (#212 ) collection.css 수정
  src/main/resources/static/css/mypage-collection.css
Labels: 🐞bugfix

#231 🌟(#146) 페이지 타이틀 변경, 아이콘 추가
  src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java
  src/main/java/com/saeromteo/app/dao/collection/CollectionDao.java
  src/main/java/com/saeromteo/app/service/collection/CollectionService.java
  src/main/java/com/saeromteo/app/service/point/PointService.java
  src/main/resources/static/icon/favicon.ico
  src/main/resources/static/icon/favicon2.ico
  src/main/webapp/WEB-INF/views/collection/footer.jsp
  src/main/webapp/WEB-INF/views/collection/header.jsp
  src/main/webapp/WEB-INF/views/collection/intro.jsp
  src/main/webapp/WEB-INF/views/collection/regist-complete.jsp
  src/main/webapp/WEB-INF/views/collection/regist-submit.jsp
  src/main/webapp/WEB-INF/views/collection/regist.jsp
  src/main/webapp/WEB-INF/views/collection/request-complete.jsp
  src/main/webapp/WEB-INF/views/collection/request-submit.jsp
  src/main/webapp/WEB-INF/views/collection/request.jsp
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-collection.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-order-detail.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-order-list.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-order-return.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-point.jsp
Labels: 🎨design, 🔄️refactoring

#233 🌟(#148 ) 디자인 변경, 타이틀 변경
  src/main/resources/static/css/style.css
  src/main/webapp/WEB-INF/views/admin/notice-manager.jsp
  src/main/webapp/WEB-INF/views/admin/question-manager.jsp
  src/main/webapp/WEB-INF/views/collection/header.jsp
  src/main/webapp/WEB-INF/views/faq/faq.jsp
  src/main/webapp/WEB-INF/views/notice/notice.jsp
  src/main/webapp/WEB-INF/views/question/question-user.jsp
  src/main/webapp/WEB-INF/views/question/question-write.jsp
  src/main/webapp/WEB-INF/views/question/question.jsp
Labels: 🎨design

#238 🌟(#148 ) 메인페이지 폰트 사이즈 변경
  src/main/resources/static/css/main.css
Labels: 🎨design

#240 헤더 로그인 버튼 사이즈
  src/main/webapp/WEB-INF/views/collection/header.jsp
Labels: 🎨design

#245 🌟(#163 ) 헤더 팝업(+css) , 리뷰, 퀴즈 bugfix, envdata,collection, 상품검색
  src/main/java/com/saeromteo/app/controller/mypage/MyPageApiController.java
  src/main/java/com/saeromteo/app/controller/review/ReviewFrontController.java
  src/main/resources/mybatis/mappers/quizMapper.xml
  src/main/resources/static/css/style.css
  src/main/webapp/WEB-INF/views/collection/header.jsp
  src/main/webapp/WEB-INF/views/dashboard/envdata.jsp
  src/main/webapp/WEB-INF/views/product/product-search.jsp
  src/main/webapp/WEB-INF/views/review/review.jsp
Labels: 🐞bugfix, 🎨design, 🌟feature, 🛠️fix

#246 🌟(#180) 메인, 위시리스트 수정
  src/main/java/com/saeromteo/app/controller/wishlist/WishlistController.java
  src/main/java/com/saeromteo/app/dao/wishlist/WishlistDAO.java
  src/main/java/com/saeromteo/app/service/wishlist/WishlistService.java
  src/main/resources/mybatis/mappers/wishlistMapper.xml
  src/main/resources/static/css/basket.css
  src/main/resources/static/css/wishlist.css
  src/main/webapp/WEB-INF/views/main.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-basket.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-wishlist.jsp
  src/main/webapp/WEB-INF/views/product/product-detail.jsp
  src/main/webapp/WEB-INF/views/product/product.jsp
Labels: 🐞bugfix, 🔄️refactoring

#247 🌟(#146) 수거 nav바 디자인 수정
  src/main/resources/static/css/style.css
  src/main/webapp/WEB-INF/views/collection/request-submit.jsp
Labels: 🎨design

#249 🌟(#148 ) 마이페이지 토글 이미지
  src/main/resources/static/css/style.css
Labels: 🎨design

#250 [Design]: update basket
  src/main/resources/static/css/basket.css
  src/main/webapp/WEB-INF/views/mypage/mypage-basket.jsp
Labels: 🎨design

#251 🌟마이페이지 유저 정보 추가 및 헤더 정보 입력
  src/main/java/com/saeromteo/app/controller/basket/BasketController.java
  src/main/java/com/saeromteo/app/controller/mypage/MyPageController.java
  src/main/java/com/saeromteo/app/controller/review/ReviewFrontController.java
  src/main/java/com/saeromteo/app/controller/wishlist/WishlistController.java
  src/main/webapp/WEB-INF/views/collection/header.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-basket.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-wishlist.jsp
  src/main/webapp/WEB-INF/views/review/review.jsp
Labels: 🎨design

#255 수거 알림 수정 및 url 수정
  src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java
  src/main/java/com/saeromteo/app/service/collection/CollectionService.java
  src/main/java/com/saeromteo/app/util/InspectionUtil.java
  src/main/resources/mybatis/mappers/collectionMapper.xml
  src/main/webapp/WEB-INF/views/collection/header.jsp
  src/main/webapp/WEB-INF/views/common/mypage-nav.jsp
  src/main/webapp/WEB-INF/views/main.jsp
Labels: 🐞bugfix, 🎨design

#259 🌟(#148 ) admin 페이지
  src/main/java/com/saeromteo/app/controller/mypage/MyPageApiController.java
  src/main/resources/static/icon/hart.svg
  src/main/resources/static/img/error-404-monochrome.svg
  src/main/resources/static/js/scripts.js
  src/main/webapp/WEB-INF/views/admin/collection-manager.jsp
  src/main/webapp/WEB-INF/views/admin/envdata-manager.jsp
  src/main/webapp/WEB-INF/views/admin/nav.jsp
  src/main/webapp/WEB-INF/views/admin/news-manager.jsp
  src/main/webapp/WEB-INF/views/admin/point-manager.jsp
  src/main/webapp/WEB-INF/views/admin/product-category-manager.jsp
  src/main/webapp/WEB-INF/views/admin/product-discount-manager.jsp
  src/main/webapp/WEB-INF/views/admin/product-manager.jsp
  src/main/webapp/WEB-INF/views/admin/quiz-manager.jsp
  src/main/webapp/WEB-INF/views/admin/review-manager.jsp
  src/main/webapp/WEB-INF/views/admin/side-nav.jsp
  src/main/webapp/WEB-INF/views/common/401error.jsp
  src/main/webapp/WEB-INF/views/common/404error.jsp
  src/main/webapp/WEB-INF/views/common/500error.jsp
  src/main/webapp/WEB-INF/web.xml
Labels: 🎨design, 🌟feature

#263 🌟(#180) 주문 데이터 전송 수정
  src/main/webapp/WEB-INF/views/mypage/mypage-basket.jsp
Labels: 🐞bugfix

#265 수거 ai 연동정보 변경
  .factorypath
  src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java
  src/main/java/com/saeromteo/app/service/collection/CollectionService.java
Labels: 🐞bugfix

#279 🌟문의사항 문의내용 사진크기 조절
  src/main/resources/static/css/question.css
Labels: 🎨design

#282 주문 내역 오류 수정
  src/main/java/com/saeromteo/app/controller/mypage/MyPageController.java
Labels: 🐞bugfix

#286 🌟(#163 ) envdetail 내용 출력 오류 수정
  src/main/resources/static/css/envdetail.css
  src/main/webapp/WEB-INF/views/admin/envdata-manager.jsp
  src/main/webapp/WEB-INF/views/dashboard/envdata.jsp
Labels: 🐞bugfix
