Repository Saerom-teo/server, pull requests merged in 2024-06, with the labels that each got.

#35 🌟(#28) sqlconfig파일 분리
  src/main/java/com/saeromteo/app/controller/order/OrderController.java
  src/main/java/com/saeromteo/app/controller/order/PaymentsController.java
  src/main/java/com/saeromteo/app/dao/EnvDataDao.java
  src/main/java/com/saeromteo/app/dao/NewsDao.java
  src/main/java/com/saeromteo/app/dao/QuizDao.java
  src/main/java/com/saeromteo/app/dao/notice/NoticeDAO.java
  src/main/java/com/saeromteo/app/dao/order/OrderDao.java
  src/main/java/com/saeromteo/app/dao/pay/PayDao.java
  src/main/java/com/saeromteo/app/dao/question/QuestionDAO.java
  src/main/java/com/saeromteo/app/model/order/OrderDetailDto.java
  src/main/java/com/saeromteo/app/model/order/OrderDto.java
  src/main/java/com/saeromteo/app/model/order/OrderSuccessDto.java
  src/main/resources/mybatis/OrderSqlMapConfig.xml
  src/main/resources/mybatis/SqlMapConfig.xml
  src/main/resources/mybatis/mappers/orderMapper.xml
  src/main/resources/mybatis/mappers/questionDao.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/payments/portoneTest.jsp
Labels: 🌟feature

#37 🌟(#33 ) 상품후기 crud
  src/main/java/com/saeromteo/app/controller/notice/NoticeController.java
  src/main/java/com/saeromteo/app/controller/question/QuestionController.java
  src/main/java/com/saeromteo/app/dao/notice/NoticeDAO.java
  src/main/java/com/saeromteo/app/dao/notice/NoticeDAOInterface.java
  src/main/java/com/saeromteo/app/dao/question/QuestionDAO.java
  src/main/java/com/saeromteo/app/dao/question/QuestionDAOInterface.java
  src/main/java/com/saeromteo/app/dao/review/ReviewDao.java
  src/main/java/com/saeromteo/app/dao/review/ReviewInterface.java
  src/main/java/com/saeromteo/app/dto/notice/NoticeDTO.java
  src/main/java/com/saeromteo/app/dto/notice/NoticeEntity.java
  src/main/java/com/saeromteo/app/dto/question/QuestionDTO.java
  src/main/java/com/saeromteo/app/dto/review/ReviewDto.java
  src/main/java/com/saeromteo/app/dto/review/ReviewEntity.java
  src/main/java/com/saeromteo/app/service/notice/NoticeService.java
  src/main/java/com/saeromteo/app/service/question/QuestionService.java
  src/main/resources/mybatis/SqlMapConfig.xml
  src/main/resources/mybatis/mappers/noticeMapper.xml
  src/main/resources/mybatis/mappers/questionMapper.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
Labels: 🌟feature

#47 🌟(#27) package 변경
  src/main/java/com/saeromteo/app/controller/envdata/EnvDataController.java
  src/main/java/com/saeromteo/app/controller/news/NewsController.java
  src/main/java/com/saeromteo/app/controller/quiz/QuizController.java
  src/main/java/com/saeromteo/app/dao/envdata/EnvDataDao.java
  src/main/java/com/saeromteo/app/dao/news/NewsDao.java
  src/main/java/com/saeromteo/app/dao/quiz/QuizDao.java
  src/main/java/com/saeromteo/app/service/envdata/EnvDataService.java
  src/main/java/com/saeromteo/app/service/news/NewsService.java
  src/main/java/com/saeromteo/app/service/quiz/QuizService.java
Labels: 🌟feature

#45 🌟(#33 ) DTO변수명 수정, vo생성
  src/main/java/com/saeromteo/app/controller/question/QuestionController.java
  src/main/java/com/saeromteo/app/dao/envdata/EnvDataDao.java
  src/main/java/com/saeromteo/app/dao/notice/NoticeDAO.java
  src/main/java/com/saeromteo/app/dao/question/QuestionDAO.java
  src/main/java/com/saeromteo/app/dto/question/QuestionDTO.java
  src/main/resources/mybatis/QuestionSqlMapConfig.xml
  src/main/resources/mybatis/mappers/noticeMapper.xml
  src/main/resources/mybatis/mappers/questionMapper.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
Labels: 🌟feature

#44 🌟(#42) Swagger 적용
  pom.xml
  src/main/java/com/saeromteo/app/config/SwaggerConfig.java
  src/main/java/com/saeromteo/app/controller/collection/CollectionController.java
  src/main/java/com/saeromteo/app/model/collection/CollectionDto.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Labels: 🌟feature

#46 🌟(#28) 주문 정보 전달
  src/main/java/com/saeromteo/app/controller/order/OrderController.java
  src/main/java/com/saeromteo/app/controller/order/PaymentsController.java
  src/main/java/com/saeromteo/app/dao/order/OrderDao.java
  src/main/java/com/saeromteo/app/dao/order/OrderDaoInterface.java
  src/main/java/com/saeromteo/app/dao/order/PaymentDao.java
  src/main/java/com/saeromteo/app/dao/order/PaymentDaoInterface.java
  src/main/java/com/saeromteo/app/model/order/RecipientInfoDto.java
  src/main/java/com/saeromteo/app/service/order/OrderService.java
  src/main/java/com/saeromteo/app/service/order/PaymentService.java
  src/main/resources/mybatis/SqlMapConfig.xml
  src/main/resources/mybatis/mappers/orderMapper.xml
  src/main/webapp/WEB-INF/views/payments/portoneTest.jsp
Labels: 🌟feature

#54 🌟(#33) 상품후기 crud
  src/main/java/com/saeromteo/app/controller/review/ReviewController.java
  src/main/java/com/saeromteo/app/dao/envdata/EnvDataDao.java
  src/main/java/com/saeromteo/app/dao/review/ReviewDao.java
  src/main/java/com/saeromteo/app/service/review/ReviewService.java
  src/main/resources/mybatis/ReviewSqlMapConfig.xml
  src/main/resources/mybatis/mappers/reviewMapper.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
Labels: 🌟feature

#55 🌟(#8 ) 상품 crud
  src/main/java/com/saeromteo/app/dto/product/ProductDTO.java
  src/main/resources/mybatis/mappers/productMapper.xml
Labels: 🔄️refactoring

#58 🌟(#50) 위시리스트 crud
  src/main/java/com/saeromteo/app/controller/wishlist/WishlistController.java
  src/main/java/com/saeromteo/app/dao/wishlist/WishlistDAO.java
  src/main/java/com/saeromteo/app/dto/wishlist/WishlistDTO.java
  src/main/java/com/saeromteo/app/service/wishlist/WishlistService.java
  src/main/resources/mybatis/WishlistSqlMapConfig.xml
  src/main/resources/mybatis/mappers/WishlistMapper.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
Labels: 🌟feature

#63 🌟(#28) 재고 체크 기능 구현
  src/main/java/com/saeromteo/app/controller/order/OrderController.java
  src/main/java/com/saeromteo/app/dao/order/OrderDao.java
  src/main/java/com/saeromteo/app/service/order/OrderService.java
  src/main/java/com/saeromteo/app/service/order/PaymentService.java
  src/main/resources/mybatis/mappers/orderMapper.xml
  src/main/webapp/WEB-INF/views/order/order.html
  src/main/webapp/WEB-INF/views/order/orderpage.jsp
  src/main/webapp/WEB-INF/views/order/portoneTest.jsp
  src/main/webapp/WEB-INF/views/order/styles.css
Labels: 🌟feature

#71 🌟(#66) 수거 신청, 등록 기능 구현
  src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java
  src/main/java/com/saeromteo/app/controller/collection/CollectionController.java
  src/main/java/com/saeromteo/app/model/collection/CollectionDto.java
  src/main/java/com/saeromteo/app/service/collection/CollectionService.java
  src/main/resources/static/js/address_input.js
  src/main/resources/static/js/image_upload.js
  src/main/webapp/WEB-INF/html/collection.html
  src/main/webapp/WEB-INF/views/collection/collection.html
  src/main/webapp/WEB-INF/views/collection/registration.jsp
  src/main/webapp/WEB-INF/views/collection/request.jsp
  src/main/webapp/WEB-INF/views/collection/test.html
Labels: 🌟feature

#72 🌟(#67 ) 공지사항 jsp, css
  src/main/java/com/saeromteo/app/controller/notice/NoticeController.java
  src/main/resources/static/css/notice1.css
  src/main/resources/static/js/notice1.js
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/notice/notice1.jsp
Labels: 🎨design

#74 🌟(#64 ) 상품, 상품카테고리, 위시리스트, 후기 수정
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/java/com/saeromteo/app/controller/review/ReviewController.java
  src/main/java/com/saeromteo/app/controller/wishlist/WishlistController.java
  src/main/java/com/saeromteo/app/dao/product/ProductDAO.java
  src/main/java/com/saeromteo/app/dao/review/ReviewDao.java
  src/main/java/com/saeromteo/app/dao/review/ReviewInterface.java
  src/main/java/com/saeromteo/app/dao/wishlist/WishlistDAO.java
  src/main/java/com/saeromteo/app/dto/product/ProductCategoryDTO.java
  src/main/java/com/saeromteo/app/dto/product/ProductDTO.java
  src/main/java/com/saeromteo/app/dto/review/ReviewDto.java
  src/main/java/com/saeromteo/app/service/product/ProductService.java
  src/main/java/com/saeromteo/app/service/review/ReviewService.java
  src/main/java/com/saeromteo/app/service/wishlist/WishlistService.java
  src/main/resources/mybatis/ReviewSqlMapConfig.xml
  src/main/resources/mybatis/mappers/basketMapper.xml
  src/main/resources/mybatis/mappers/discountMapper.xml
  src/main/resources/mybatis/mappers/productCategoryMapper.xml
  src/main/resources/mybatis/mappers/productMapper.xml
  src/main/resources/mybatis/mappers/reviewMapper.xml
  src/main/resources/mybatis/mappers/wishlistMapper.xml
Labels: 🌟feature, 🔄️refactoring

#76 🌟(#28) 페이지 전환 시 데이터 전달
  src/main/java/com/saeromteo/app/controller/order/OrderController.java
  src/main/java/com/saeromteo/app/controller/order/PaymentsController.java
  src/main/java/com/saeromteo/app/model/order/OrderDetailDto.java
  src/main/java/com/saeromteo/app/model/order/OrderDto.java
  src/main/java/com/saeromteo/app/model/order/OrderProductDto.java
  src/main/java/com/saeromteo/app/model/order/OrderProductEntity.java
  src/main/java/com/saeromteo/app/model/order/OrderStatus.java
  src/main/java/com/saeromteo/app/service/order/OrderService.java
  src/main/java/com/saeromteo/app/service/order/PaymentService.java
  src/main/resources/mybatis/mappers/orderMapper.xml
  src/main/resources/static/css/styles.css
  src/main/webapp/WEB-INF/views/order/orderpage.jsp
  src/main/webapp/WEB-INF/views/order/styles.css
  src/main/webapp/WEB-INF/views/order/test.jsp
Labels: 🌟feature

#77 🌟(#65)(#73) 프론트 헤더, 푸터, notice
  src/main/java/com/saeromteo/app/controller/TestController.java
  src/main/java/com/saeromteo/app/controller/news/NewsController.java
  src/main/resources/static/css/dashboard.css
  src/main/resources/static/css/header.css
  src/main/resources/static/css/notice.css
  src/main/resources/static/img/User.svg
  src/main/resources/static/img/b.svg
  src/main/resources/static/img/basket.svg
  src/main/resources/static/img/facebook.svg
  src/main/resources/static/img/instagram.svg
  src/main/resources/static/img/logo.svg
  src/main/resources/static/img/notice-img.png
  src/main/resources/static/img/notice.svg
  src/main/resources/static/img/search.svg
  src/main/resources/static/img/x.svg
  src/main/resources/static/img/zzim.svg
  src/main/webapp/WEB-INF/views/auth/login.jsp
  src/main/webapp/WEB-INF/views/common/footer.jsp
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/dashboard/dashboard.jsp
  src/main/webapp/WEB-INF/views/notice/notice.jsp
Labels: 🎨design, 🌟feature

#78 🌟(#72 ) notice variable
  src/main/java/com/saeromteo/app/controller/review/ReviewController.java
  src/main/java/com/saeromteo/app/dao/review/ReviewDao.java
  src/main/java/com/saeromteo/app/dao/review/ReviewInterface.java
  src/main/java/com/saeromteo/app/dto/review/ReviewDto.java
  src/main/java/com/saeromteo/app/service/review/ReviewService.java
  src/main/resources/mybatis/ReviewSqlMapConfig.xml
Labels: 🐞bugfix

#84 🌟(#66) 수거 신청, 등록 기능 구현
  pom.xml
  src/main/java/com/saeromteo/app/config/AppConfig.java
  src/main/java/com/saeromteo/app/config/S3Config.java
  src/main/java/com/saeromteo/app/config/SecurityConfig.java
  src/main/java/com/saeromteo/app/config/SwaggerConfig.java
  src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java
  src/main/java/com/saeromteo/app/model/collection/AiDto.java
  src/main/java/com/saeromteo/app/model/collection/CollectionDto.java
  src/main/java/com/saeromteo/app/service/collection/CollectionService.java
  src/main/java/com/saeromteo/app/util/S3Util.java
  src/main/webapp/WEB-INF/views/collection/request.jsp
Labels: 🌟feature

#85 🌟(#82, #73) figma -> 코드화 / 퀴즈 기능
  src/main/java/com/saeromteo/app/controller/TestController.java
  src/main/java/com/saeromteo/app/controller/quiz/QuizApiController.java
  src/main/java/com/saeromteo/app/controller/quiz/QuizFrontController.java
  src/main/java/com/saeromteo/app/dao/quiz/QuizDao.java
  src/main/java/com/saeromteo/app/dto/point/EarningPointDto.java
  src/main/java/com/saeromteo/app/model/quiz/QuizEntity.java
  src/main/java/com/saeromteo/app/model/quiz/QuizHistoryEntity.java
  src/main/java/com/saeromteo/app/service/quiz/QuizService.java
  src/main/resources/mybatis/QuizSqlMapConfig.xml
  src/main/resources/mybatis/mappers/quizMapper.xml
  src/main/resources/static/css/complete.css
  src/main/resources/static/css/envdata.css
  src/main/resources/static/css/envdetail.css
  src/main/resources/static/css/header.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/mypage-nav.css
  src/main/resources/static/css/mypage-orderlist.css
  src/main/resources/static/css/news.css
  src/main/resources/static/css/newsnav.css
  src/main/resources/static/css/quiz.css
  src/main/resources/static/css/shopdetail.css
  src/main/resources/static/css/shopnav.css
  src/main/resources/static/css/shoppingmall.css
  src/main/resources/static/css/vars.css
  src/main/resources/static/img/apple.svg
  src/main/resources/static/img/banner-img-1.png
  src/main/resources/static/img/banner-img-2.png
  src/main/resources/static/img/detail-img.png
  src/main/resources/static/img/envdetail-img1.png
  src/main/resources/static/img/hart.svg
  src/main/resources/static/img/main-img-0.png
  src/main/resources/static/img/main-img-1.png
  src/main/resources/static/img/main-img-2.png
  src/main/resources/static/img/mypage-image1.png
  src/main/resources/static/img/mypage-profile.svg
  src/main/resources/static/img/news-image1.png
  src/main/resources/static/img/product-img.png
  src/main/resources/static/img/tree.png
  src/main/webapp/WEB-INF/views/common/header.jsp
  src/main/webapp/WEB-INF/views/common/mypage-nav.jsp
  src/main/webapp/WEB-INF/views/common/newsnav.jsp
  src/main/webapp/WEB-INF/views/common/shopnav.jsp
  src/main/webapp/WEB-INF/views/dashboard/envdata.jsp
  src/main/webapp/WEB-INF/views/dashboard/envdetail.jsp
  src/main/webapp/WEB-INF/views/dashboard/news.jsp
  src/main/webapp/WEB-INF/views/dashboard/quiz.jsp
  src/main/webapp/WEB-INF/views/main2.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-orderlist.jsp
  src/main/webapp/WEB-INF/views/shop/complete.jsp
  src/main/webapp/WEB-INF/views/shop/shopdetail.jsp
  src/main/webapp/WEB-INF/views/shop/shoppingmall.jsp
Labels: 🌟feature

#86 🌟(#79) 장바구니, 위시리스트 수정
  src/main/java/com/saeromteo/app/controller/basket/BasketController.java
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/java/com/saeromteo/app/controller/review/ReviewController.java
  src/main/java/com/saeromteo/app/controller/wishlist/WishlistController.java
  src/main/resources/mybatis/mappers/basketMapper.xml
  src/main/resources/static/css/basket.css
  src/main/resources/static/css/review.css
  src/main/resources/static/css/wishlist.css
  src/main/resources/static/img/date.svg
  src/main/resources/static/img/heart.svg
  src/main/resources/static/img/left.svg
  src/main/resources/static/img/right.svg
  src/main/resources/static/img/tower.png
  src/main/webapp/WEB-INF/views/basket/basket.jsp
  src/main/webapp/WEB-INF/views/review/review.jsp
  src/main/webapp/WEB-INF/views/wishlist/wishlist.jsp
Labels: 🎨design, 🌟feature

#88 🌟(#67 ) notice, question, FAQ front 작업
  src/main/java/com/saeromteo/app/controller/notice/NoticeController.java
  src/main/java/com/saeromteo/app/controller/question/QuestionController.java
  src/main/java/com/saeromteo/app/dao/notice/NoticeDAO.java
  src/main/java/com/saeromteo/app/service/notice/NoticeService.java
  src/main/resources/static/css/faq.css
  src/main/resources/static/css/question.css
  src/main/resources/static/js/faq.js
  src/main/resources/static/js/notice.js
  src/main/webapp/WEB-INF/views/faq/faq.jsp
  src/main/webapp/WEB-INF/views/notice/notice.jsp
  src/main/webapp/WEB-INF/views/question/question-write.jsp
  src/main/webapp/WEB-INF/views/question/question.jsp
Labels: 🌟feature

#89 🌟(#67) editor 디자인
  src/main/java/com/saeromteo/app/controller/editor/EditorController.java
  src/main/resources/mybatis/mappers/discountMapper.xml
  src/main/resources/mybatis/mappers/wishlistMapper.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/editor/editor.jsp
  src/main/webapp/WEB-INF/views/editor/editor2.jsp
  src/main/webapp/WEB-INF/views/editor/editortest.jsp
  src/main/webapp/WEB-INF/web.xml
Labels: 🎨design

#90 🌟(#67 ) editor css 적용
  src/main/java/com/saeromteo/app/controller/editor/EditorController.java
  src/main/resources/static/css/question.css
  src/main/webapp/WEB-INF/views/question/question-write.jsp
Labels: 🎨design

#94 🌟(#79 ) 장바구니, 후기 프론트
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/java/com/saeromteo/app/controller/review/ReviewController.java
  src/main/resources/static/css/basket.css
  src/main/resources/static/css/product-detail-review.css
  src/main/resources/static/css/review.css
  src/main/resources/static/css/wishlist.css
  src/main/resources/static/img/User_cicrle_light.svg
  src/main/resources/static/img/son.png
  src/main/resources/static/img/star.svg
  src/main/resources/static/img/star2.svg
  src/main/resources/static/img/tower.png
  src/main/resources/static/js/basket.js
  src/main/webapp/WEB-INF/views/basket/basket.jsp
  src/main/webapp/WEB-INF/views/common/mypage-nav.jsp
  src/main/webapp/WEB-INF/views/product/product-detail-review.jsp
  src/main/webapp/WEB-INF/views/review/review.jsp
  src/main/webapp/WEB-INF/views/wishlist/wishlist.jsp
Labels: 🎨design

#93 🌟(#81) 수거 프론트 제작1
  src/main/java/com/saeromteo/app/controller/collection/CollectionController.java
  src/main/resources/static/css/collection.css
  src/main/resources/static/css/style.css
  src/main/resources/static/css/vars.css
  src/main/resources/static/icon/b.svg
  src/main/resources/static/icon/basket.svg
  src/main/resources/static/icon/facebook.svg
  src/main/resources/static/icon/instagram.svg
  src/main/resources/static/icon/logo.svg
  src/main/resources/static/icon/notice.svg
  src/main/resources/static/icon/search.svg
  src/main/resources/static/icon/user.svg
  src/main/resources/static/icon/x.svg
  src/main/resources/static/icon/zzim.svg
  src/main/resources/static/image/collection/collection-items.png
  src/main/resources/static/image/collection/eco-cycle.png
  src/main/resources/static/image/collection/garbage.png
  src/main/resources/static/image/collection/join.png
  src/main/resources/static/image/collection/map.png
  src/main/resources/static/image/collection/title.png
  src/main/webapp/WEB-INF/html/collection.html
  src/main/webapp/WEB-INF/views/collection/collection-nav.jsp
  src/main/webapp/WEB-INF/views/collection/collection.html
  src/main/webapp/WEB-INF/views/collection/footer.jsp
  src/main/webapp/WEB-INF/views/collection/header.jsp
  src/main/webapp/WEB-INF/views/collection/intro.jsp
  src/main/webapp/WEB-INF/views/collection/regist.jsp
  src/main/webapp/WEB-INF/views/collection/registration.jsp
  src/main/webapp/WEB-INF/views/collection/request-submit.jsp
  src/main/webapp/WEB-INF/views/collection/request.jsp
  src/main/webapp/WEB-INF/views/collection/test.html
Labels: 🎨design, 🌟feature

#99 🌟(#67 ) 에디터, 페이징
  src/main/java/com/saeromteo/app/controller/editor/EditorController.java
  src/main/java/com/saeromteo/app/controller/question/QuestionController.java
  src/main/java/com/saeromteo/app/dao/question/QuestionDAO.java
  src/main/java/com/saeromteo/app/dto/question/QuestionDTO.java
  src/main/java/com/saeromteo/app/service/question/QuestionService.java
  src/main/resources/mybatis/mappers/questionMapper.xml
  src/main/webapp/WEB-INF/views/editor/editor.jsp
  src/main/webapp/WEB-INF/views/editor/editor2.jsp
  src/main/webapp/WEB-INF/views/editor/editortest.jsp
  src/main/webapp/WEB-INF/views/question/question-write.jsp
  src/main/webapp/WEB-INF/views/question/question.jsp
Labels: 🌟feature

#101 🌟(#79 ) 상품 프론트
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/java/com/saeromteo/app/dto/product/ProductDTO.java
  src/main/resources/mybatis/mappers/productMapper.xml
  src/main/resources/static/css/basket.css
  src/main/resources/static/css/mypage-nav.css
  src/main/resources/static/css/product-detail-review.css
  src/main/resources/static/css/review.css
  src/main/resources/static/css/shopnav.css
  src/main/resources/static/css/shoppingmall.css
  src/main/resources/static/css/wishlist.css
  src/main/resources/static/js/product.js
  src/main/webapp/WEB-INF/views/common/mypage-nav.jsp
  src/main/webapp/WEB-INF/views/common/shopnav.jsp
  src/main/webapp/WEB-INF/views/product/product-detail-review.jsp
  src/main/webapp/WEB-INF/views/product/product.jsp
  src/main/webapp/WEB-INF/views/review/review.jsp
  src/main/webapp/WEB-INF/views/shop/shoppingmall.jsp
Labels: 🎨design, 🌟feature

#102 🌟(#95) 환경자료 만들기
  pom.xml
  src/main/java/com/saeromteo/app/controller/TestController.java
  src/main/java/com/saeromteo/app/controller/envdata/EnvDataApiController.java
  src/main/java/com/saeromteo/app/controller/envdata/EnvDataFrontController.java
  src/main/java/com/saeromteo/app/controller/quiz/QuizFrontController.java
  src/main/java/com/saeromteo/app/dao/envdata/EnvDataDao.java
  src/main/java/com/saeromteo/app/dto/envdata/EnvironmentDataDto.java
  src/main/java/com/saeromteo/app/model/envdata/EnvDataEntity.java
  src/main/java/com/saeromteo/app/service/envdata/EnvDataService.java
  src/main/java/com/saeromteo/app/service/markdown/MarkdownService.java
  src/main/resources/mybatis/mappers/envDataMapper.xml
  src/main/resources/static/css/envdata.css
  src/main/resources/static/css/envdetail.css
  src/main/resources/static/css/quiz.css
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/admin/createEnvData.jsp
  src/main/webapp/WEB-INF/views/dashboard/envdata.jsp
  src/main/webapp/WEB-INF/views/dashboard/envdetail.jsp
  src/main/webapp/WEB-INF/views/dashboard/quiz.jsp
Labels: 🌟feature

#105 🌟(#95) 환경 자료 기능 완성하기
  src/main/java/com/saeromteo/app/controller/dashboard/DashboardController.java
  src/main/java/com/saeromteo/app/controller/news/NewsApiController.java
  src/main/java/com/saeromteo/app/controller/news/NewsFrontController.java
  src/main/resources/mybatis/mappers/envDataMapper.xml
  src/main/resources/static/css/envdata.css
  src/main/webapp/WEB-INF/views/admin/createEnvData.jsp
  src/main/webapp/WEB-INF/views/dashboard/dashboard.jsp
  src/main/webapp/WEB-INF/views/dashboard/envdata.jsp
Labels: 🌟feature

#106 🌟(#79 ) 상품, 장바구니 페이지 구현
  src/main/java/com/saeromteo/app/controller/basket/BasketController.java
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/java/com/saeromteo/app/dao/product/ProductDAO.java
  src/main/java/com/saeromteo/app/dto/product/ProductDTO.java
  src/main/java/com/saeromteo/app/service/product/ProductService.java
  src/main/resources/mybatis/mappers/productMapper.xml
  src/main/resources/static/css/product-detail-review.css
  src/main/resources/static/css/product.css
  src/main/resources/static/js/basket.js
  src/main/webapp/WEB-INF/views/basket/basket.jsp
  src/main/webapp/WEB-INF/views/product/product-detail.jsp
  src/main/webapp/WEB-INF/views/product/product.jsp
Labels: 🌟feature

#107 🌟(#28) 결제 직전 세부 기능 구현
  src/main/java/com/saeromteo/app/controller/order/OrderController.java
  src/main/java/com/saeromteo/app/controller/order/PaymentsController.java
  src/main/java/com/saeromteo/app/dao/order/OrderDao.java
  src/main/java/com/saeromteo/app/model/order/OrderProductDto.java
  src/main/java/com/saeromteo/app/model/order/RecipientInfoDto.java
  src/main/java/com/saeromteo/app/service/order/OrderService.java
  src/main/java/com/saeromteo/app/service/order/PaymentService.java
  src/main/resources/mybatis/OrderSqlMapConfig.xml
  src/main/resources/mybatis/mappers/orderMapper.xml
  src/main/resources/static/css/order.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/img/producTest.png
  src/main/webapp/WEB-INF/views/order/orderpage.jsp
  src/main/webapp/WEB-INF/views/order/test.jsp
Labels: 🌟feature

#112 🌟(#67) editor 끝, 필터링
  src/main/java/com/saeromteo/app/controller/notice/NoticeController.java
  src/main/java/com/saeromteo/app/controller/question/FileApiController.java
  src/main/java/com/saeromteo/app/controller/question/QuestionController.java
  src/main/java/com/saeromteo/app/dao/notice/NoticeDAO.java
  src/main/java/com/saeromteo/app/dao/question/QuestionDAO.java
  src/main/java/com/saeromteo/app/dto/notice/NoticeDTO.java
  src/main/java/com/saeromteo/app/dto/question/QuestionDTO.java
  src/main/java/com/saeromteo/app/service/notice/NoticeService.java
  src/main/java/com/saeromteo/app/service/question/QuestionService.java
  src/main/resources/mybatis/QuestionSqlMapConfig.xml
  src/main/resources/mybatis/ReviewSqlMapConfig.xml
  src/main/resources/mybatis/mappers/noticeMapper.xml
  src/main/resources/mybatis/mappers/questionMapper.xml
  src/main/resources/mybatis/mappers/reviewMapper.xml
  src/main/resources/static/css/faq.css
  src/main/resources/static/css/notice.css
  src/main/resources/static/css/question.css
  src/main/resources/static/js/notice.js
  src/main/webapp/WEB-INF/views/faq/faq.jsp
  src/main/webapp/WEB-INF/views/notice/notice.jsp
  src/main/webapp/WEB-INF/views/question/question-write.jsp
  src/main/webapp/WEB-INF/views/question/question.jsp
Labels: 🌟feature

#111 🌟(#110) 관리자 페이지 제작
  src/main/java/com/saeromteo/app/controller/admin/AdminApiController.java
  src/main/java/com/saeromteo/app/controller/admin/AdminController.java
  src/main/java/com/saeromteo/app/model/collection/CollectionEntity.java
  src/main/java/com/saeromteo/app/service/collection/CollectionService.java
  src/main/resources/static/css/admin-styles.css
  src/main/resources/static/js/admin/datatables-simple-demo.js
  src/main/resources/static/js/admin/scripts.js
  src/main/webapp/WEB-INF/views/admin/collection-manager.jsp
  src/main/webapp/WEB-INF/views/admin/dashboard.jsp
  src/main/webapp/WEB-INF/views/admin/nav.jsp
  src/main/webapp/WEB-INF/views/admin/side-nav.jsp
Labels: 🌟feature

#117 🌟(#110) s3 파일 업로드에 type 추가
  src/main/java/com/saeromteo/app/service/collection/CollectionService.java
  src/main/java/com/saeromteo/app/util/S3Util.java
  src/main/resources/static/js/admin/scripts.js
Labels: 🔄️refactoring

#116 🌟(#28) 주문 및 결제 기능 구현
  src/main/java/com/saeromteo/app/controller/order/OrderController.java
  src/main/java/com/saeromteo/app/controller/order/PaymentsController.java
  src/main/java/com/saeromteo/app/dao/order/OrderDao.java
  src/main/java/com/saeromteo/app/model/order/RecipientInfoDto.java
  src/main/java/com/saeromteo/app/service/order/OrderService.java
  src/main/java/com/saeromteo/app/service/order/PaymentService.java
  src/main/resources/mybatis/mappers/orderMapper.xml
  src/main/resources/static/css/order.css
  src/main/resources/static/img/kakaopay_payment.png
  src/main/resources/static/img/payco_payment.png
  src/main/resources/static/js/address_input.js
  src/main/webapp/WEB-INF/views/order/orderpage.jsp
  src/main/webapp/WEB-INF/views/order/test.jsp
Labels: 🌟feature

#118 🌟(#103 #104 #113) 뉴스, 대시보드 완성 어드민 시도
  src/main/java/com/saeromteo/app/controller/admin/AdminController.java
  src/main/java/com/saeromteo/app/controller/dashboard/DashboardController.java
  src/main/java/com/saeromteo/app/controller/news/NewsApiController.java
  src/main/java/com/saeromteo/app/controller/news/NewsFrontController.java
  src/main/java/com/saeromteo/app/dao/envdata/EnvDataDao.java
  src/main/java/com/saeromteo/app/dao/news/NewsDao.java
  src/main/java/com/saeromteo/app/dao/quiz/QuizDao.java
  src/main/java/com/saeromteo/app/dto/news/NewsDto.java
  src/main/java/com/saeromteo/app/model/news/NewsEntity.java
  src/main/java/com/saeromteo/app/service/envdata/EnvDataService.java
  src/main/java/com/saeromteo/app/service/news/NewsService.java
  src/main/resources/mybatis/mappers/envDataMapper.xml
  src/main/resources/mybatis/mappers/newsMapper.xml
  src/main/resources/mybatis/mappers/quizMapper.xml
  src/main/resources/static/css/dashboard.css
  src/main/resources/static/css/news.css
  src/main/resources/static/icon/news_up.png
  src/main/webapp/WEB-INF/views/admin/news-manager.jsp
  src/main/webapp/WEB-INF/views/admin/side-nav.jsp
  src/main/webapp/WEB-INF/views/dashboard/dashboard.jsp
  src/main/webapp/WEB-INF/views/dashboard/news.jsp
Labels: 🌟feature

#123 🌟(#122 ) mysql listener 오탈자 수정
  src/main/webapp/WEB-INF/web.xml
Labels: 🐞bugfix

#126 🌟(#97) 수거 요청 결과 저장 로직 수정
  src/main/java/com/saeromteo/app/config/AppConfig.java
  src/main/java/com/saeromteo/app/config/AsyncConfig.java
  src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java
  src/main/java/com/saeromteo/app/dao/collection/CollectionDao.java
  src/main/java/com/saeromteo/app/model/collection/CollectionEntity.java
  src/main/java/com/saeromteo/app/service/collection/CollectionService.java
  src/main/java/com/saeromteo/app/util/InspectionUtil.java
  src/main/resources/mybatis/mappers/collectionMapper.xml
  src/main/resources/static/js/admin/scripts.js
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Labels: 🌟feature, 🔄️refactoring

#129 🌟(#110) 수거 신청, 요청 기본값 설정
  src/main/java/com/saeromteo/app/config/AppConfig.java
  src/main/java/com/saeromteo/app/config/SecurityConfig.java
  src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java
  src/main/java/com/saeromteo/app/dao/user/UserDAO.java
  src/main/java/com/saeromteo/app/dto/user/UserDTO.java
  src/main/java/com/saeromteo/app/dto/user/UserInfoDTO.java
  src/main/java/com/saeromteo/app/service/collection/CollectionService.java
  src/main/java/com/saeromteo/app/service/user/UserService.java
  src/main/resources/mybatis/mappers/userMapper.xml
  src/main/webapp/WEB-INF/views/admin/collection-manager.jsp
  src/main/webapp/WEB-INF/views/collection/regist-submit.jsp
  src/main/webapp/WEB-INF/views/collection/request-submit.jsp
Labels: 🌟feature

#130 🌟(#115) 주문 내역 조회
  src/main/java/com/saeromteo/app/controller/order/OrderController.java
  src/main/java/com/saeromteo/app/controller/orderInquiry/OrderInquiryController.java
  src/main/java/com/saeromteo/app/dao/order/OrderDaoInterface.java
  src/main/java/com/saeromteo/app/dao/orderInquiry/OrderInquiryDao.java
  src/main/java/com/saeromteo/app/model/order/OrderDto.java
  src/main/java/com/saeromteo/app/service/orderInquiry/OrderInquiryService.java
  src/main/resources/mybatis/OrderInquirySqlMapConfig.xml
  src/main/resources/mybatis/mappers/orderInquiryMapper.xml
  src/main/resources/static/css/orderInquiry.css
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/order/order.html
  src/main/webapp/WEB-INF/views/order/test.jsp
  src/main/webapp/WEB-INF/views/orderInquiry/orderInquiry.jsp
  src/main/webapp/WEB-INF/views/orderInquiry/orderInquiry2.jsp
Labels: 🌟feature

#131 🌟(#67 ) 검색어 필터링 수정
  src/main/java/com/saeromteo/app/dao/notice/NoticeDAO.java
  src/main/java/com/saeromteo/app/dao/question/QuestionDAO.java
  src/main/resources/static/css/faq.css
  src/main/webapp/WEB-INF/views/admin/notice-manager.jsp
  src/main/webapp/WEB-INF/views/faq/faq.jsp
Labels: 🐞bugfix

#132 🌟(#79 ) 상품, 장바구니 페이지 수정
  src/main/java/com/saeromteo/app/controller/basket/BasketController.java
  src/main/resources/mybatis/mappers/basketMapper.xml
  src/main/resources/mybatis/mappers/productMapper.xml
  src/main/webapp/WEB-INF/views/basket/basket.jsp
  src/main/webapp/WEB-INF/views/product/product-detail.jsp
Labels: 🌟feature, 🔄️refactoring

#133 🌟(#113) 메인페이지 제작
  Dockerfile
  pom.xml
  src/main/java/com/saeromteo/app/controller/MainController.java
  src/main/java/com/saeromteo/app/controller/TestController.java
  src/main/java/com/saeromteo/app/controller/news/NewsApiController.java
  src/main/java/com/saeromteo/app/util/DateUtil.java
  src/main/resources/mybatis/mappers/newsMapper.xml
  src/main/resources/static/css/main.css
  src/main/resources/static/img/banner1.png
  src/main/resources/static/img/banner2.png
  src/main/resources/static/img/banner3.png
  src/main/webapp/WEB-INF/views/dashboard/news.jsp
  src/main/webapp/WEB-INF/views/main2.jsp
Labels: 🌟feature

#134 🌟(#79 ) 장바구니 ,상품 카테고리 수정
  src/main/java/com/saeromteo/app/controller/basket/BasketController.java
  src/main/java/com/saeromteo/app/controller/product/ProductCategoryController.java
  src/main/java/com/saeromteo/app/controller/product/ProductController.java
  src/main/java/com/saeromteo/app/dao/product/ProductCategoryDAO.java
  src/main/java/com/saeromteo/app/dao/product/ProductDAO.java
  src/main/java/com/saeromteo/app/model/product/ProductCategoryEntity.java
  src/main/java/com/saeromteo/app/service/product/ProductCategoryService.java
  src/main/java/com/saeromteo/app/service/product/ProductService.java
  src/main/resources/mybatis/mappers/productCategoryMapper.xml
  src/main/resources/mybatis/mappers/productMapper.xml
  src/main/resources/static/css/product.css
  src/main/resources/static/css/shopnav.css
  src/main/resources/static/js/basket.js
  src/main/resources/static/js/product.js
  src/main/webapp/WEB-INF/views/basket/basket.jsp
  src/main/webapp/WEB-INF/views/common/shopnav.jsp
Labels: 🌟feature, 🔄️refactoring

#136 🌟(#110) 수거 완료기능 제작
  src/main/java/com/saeromteo/app/controller/admin/AdminController.java
  src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java
  src/main/java/com/saeromteo/app/controller/mypage/MyPageController.java
  src/main/java/com/saeromteo/app/dao/collection/CollectionDao.java
  src/main/java/com/saeromteo/app/model/collection/CollectionDto.java
  src/main/java/com/saeromteo/app/service/collection/CollectionService.java
  src/main/resources/mybatis/mappers/collectionMapper.xml
  src/main/resources/static/css/mypage-nav.css
  src/main/resources/static/icon/apple.svg
  src/main/resources/static/icon/mypage-profile.svg
  src/main/resources/static/js/admin/collection-manager.js
  src/main/webapp/WEB-INF/views/admin/collection-manager.jsp
  src/main/webapp/WEB-INF/views/common/mypage-nav.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-collection.jsp
Labels: 🌟feature

#137 (#9) oAuth 신규 회원 회원가입 구현 및 Login 예외처리
  src/main/java/com/saeromteo/app/controller/user/AuthController.java
  src/main/java/com/saeromteo/app/dao/user/UserDAO.java
  src/main/java/com/saeromteo/app/dto/user/PrincipalDetail.java
  src/main/java/com/saeromteo/app/dto/user/UserLoginDTO.java
  src/main/java/com/saeromteo/app/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/saeromteo/app/jwt/JwtAuthenticationFilter.java
  src/main/java/com/saeromteo/app/service/user/UserLoginService.java
  src/main/resources/mybatis/mappers/userMapper.xml
  src/main/resources/static/js/login.js
Labels: 🌟feature

#139 🌟(#113) css조금씩 수정
  src/main/resources/static/css/dashboard.css
  src/main/resources/static/css/envdetail.css
  src/main/resources/static/css/news.css
  src/main/resources/static/css/quiz.css
  src/main/webapp/WEB-INF/views/admin/createEnvData.jsp
  src/main/webapp/WEB-INF/views/admin/envdata-manager.jsp
  src/main/webapp/WEB-INF/views/admin/quiz-manager.jsp
  src/main/webapp/WEB-INF/views/common/dashboard-nav.jsp
  src/main/webapp/WEB-INF/views/dashboard/dashboard.jsp
  src/main/webapp/WEB-INF/views/dashboard/envdata.jsp
  src/main/webapp/WEB-INF/views/dashboard/news.jsp
  src/main/webapp/WEB-INF/views/dashboard/quiz.jsp
Labels: 🎨design

#140 🌟(#110) 마이페이지 수거조회 추가, 수거 관리자페이지 수정
  src/main/java/com/saeromteo/app/controller/admin/AdminController.java
  src/main/java/com/saeromteo/app/controller/collection/CollectionApiController.java
  src/main/java/com/saeromteo/app/controller/mypage/MyPageController.java
  src/main/java/com/saeromteo/app/dao/collection/CollectionDao.java
  src/main/java/com/saeromteo/app/model/collection/CollectionDto.java
  src/main/java/com/saeromteo/app/model/collection/CollectionEntity.java
  src/main/java/com/saeromteo/app/service/collection/CollectionService.java
  src/main/java/com/saeromteo/app/util/InspectionUtil.java
  src/main/resources/mybatis/mappers/collectionMapper.xml
  src/main/resources/static/css/mypage-collection.css
  src/main/resources/static/css/mypage-nav.css
  src/main/resources/static/icon/arrow.svg
  src/main/resources/static/js/admin/collection-manager.js
  src/main/resources/static/js/collection/service.js
  src/main/resources/static/js/mypage/mypage-collection.js
  src/main/webapp/WEB-INF/views/admin/collection-manager2.jsp
  src/main/webapp/WEB-INF/views/collection/collection-nav.jsp
  src/main/webapp/WEB-INF/views/collection/header.jsp
  src/main/webapp/WEB-INF/views/common/mypage-nav.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage-collection.jsp
Labels: 🎨design, 🌟feature, 🔄️refactoring

#142 🌟(#114) 문의사항
  src/main/java/com/saeromteo/app/controller/question/QuestionController.java
  src/main/java/com/saeromteo/app/dao/question/QuestionDAO.java
  src/main/java/com/saeromteo/app/dto/question/QuestionDTO.java
  src/main/java/com/saeromteo/app/service/question/QuestionService.java
  src/main/resources/mybatis/mappers/questionMapper.xml
  src/main/webapp/WEB-INF/views/admin/notice-manager.jsp
  src/main/webapp/WEB-INF/views/admin/question-manager.jsp
  src/main/webapp/WEB-INF/views/editor/editor-notice-form.jsp
  src/main/webapp/WEB-INF/views/editor/editor-question-form.jsp
  src/main/webapp/WEB-INF/views/question/question-write.jsp
Labels: 🔄️refactoring

#143 🌟(#115) 주문 내역 상세 조회
  src/main/java/com/saeromteo/app/controller/order/OrderController.java
  src/main/java/com/saeromteo/app/controller/orderInquiry/OrderInquiryController.java
  src/main/java/com/saeromteo/app/dao/orderInquiry/OrderInquiryDao.java
  src/main/java/com/saeromteo/app/model/order/DeliveryDto.java
  src/main/java/com/saeromteo/app/model/order/DetailInquiryDto.java
  src/main/java/com/saeromteo/app/model/order/OrderDetailDto.java
  src/main/java/com/saeromteo/app/service/orderInquiry/OrderInquiryService.java
  src/main/resources/mybatis/OrderInquirySqlMapConfig.xml
  src/main/resources/mybatis/mappers/orderInquiryMapper.xml
  src/main/resources/static/css/orderDetailnquriy.css
  src/main/resources/static/css/orderInquiry.css
  src/main/webapp/WEB-INF/views/orderInquiry/orderDetailnquriy.html
  src/main/webapp/WEB-INF/views/orderInquiry/orderDetailnquriy.jsp
  src/main/webapp/WEB-INF/views/orderInquiry/orderInquiry.jsp
  src/main/webapp/WEB-INF/views/orderInquiry/orderInquiry2.jsp
Labels: 🎨design, 🌟feature
